# Generated by Django 5.2.8 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('visitor_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visit_day', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
