# Generated by Django 3.1.5 on 2021-02-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('Intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBotAPI.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('Intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBotAPI.intent')),
            ],
        ),
        migrations.CreateModel(
            name='ContextSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('Intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBotAPI.intent')),
            ],
        ),
    ]
