# Generated by Django 3.1.5 on 2021-02-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBotAPI.persona')),
            ],
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='Intent',
        ),
        migrations.RemoveField(
            model_name='response',
            name='Intent',
        ),
        migrations.DeleteModel(
            name='ContextSet',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
