# Generated by Django 3.1.5 on 2021-02-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotAPI', '0002_auto_20210209_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitystatement',
            name='Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='ChatBotAPI.persona'),
        ),
    ]
