# Generated by Django 3.1.5 on 2021-02-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotAPI', '0003_auto_20210210_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalityStatement',
            new_name='Statement',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ChatBotAPI.persona')),
                ('pervious', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='ChatBotAPI.history')),
            ],
        ),
    ]
