# Generated by Django 3.1.5 on 2021-02-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotAPI', '0004_auto_20210210_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pervious',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='ChatBotAPI.history'),
        ),
    ]
